image: moodlehq/moodle-php-apache:7.0

cache:
  paths:
  - $HOME/.composer/cache

variables:
  DEBIAN_FRONTEND: "noninteractive"
  TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"
  COMPOSER_ALLOW_SUPERUSER: "1"
  MOODLE_CI_VER: "2"
  DBNAME: "moodle"
  # Change this in case you need a different moodle fork
  MOODLE_REPO: "https://github.com/moodle/moodle.git"

.build_template: &build_definition
  before_script:
    - apt-get -qq update
    - apt-get -qq --no-install-suggests --no-install-recommends install curl ca-certificates git-core gnupg software-properties-common
    - if [ "$MOODLE_CI_VER" -eq 2 ] ; then curl -sS https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - ; fi
    - if [ "$MOODLE_CI_VER" -eq 2 ] ; then add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ ; fi
    - if [ "$MOODLE_CI_VER" -eq 2 ] ; then apt-get -qq update ; fi
    - mkdir -p /usr/share/man/man1 /usr/share/man/man3 /usr/share/man/man7
    - if [ "$MOODLE_CI_VER" -eq 2 ] ; then apt-get -qq --no-install-suggests --no-install-recommends install adoptopenjdk-8-openj9-jre ; fi
    - if [ "$DB" = "mysqli"  ] ; then apt-get -qq --no-install-suggests --no-install-recommends install mysql-client ; fi
    - if [ "$DB" = "pgsql"   ] ; then apt-get -qq --no-install-suggests --no-install-recommends install postgresql-client ; fi
    - if [ "$DB" = "mariadb" ] ; then apt-get -qq --no-install-suggests --no-install-recommends install mariadb-client ; fi
    - curl -sS https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
    - . ~/.bashrc
    - nvm install --no-progress v8.9.4
    - curl -sS https://getcomposer.org/installer | php -- --install-dir='/usr/local/bin' --filename='composer'
    - touch '/usr/local/bin/phpenv' && chmod +x '/usr/local/bin/phpenv'
    - cd "$CI_PROJECT_DIR/.."
    - composer create-project -n --no-dev --no-progress --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^$MOODLE_CI_VER
    - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
    - moodle-plugin-ci install --db-user="$DBUSER" --db-pass="$DBPASS" --db-host="$DBHOST" --db-name="$DBNAME"
  script:
    - moodle-plugin-ci phplint
    - moodle-plugin-ci phpcpd
    - moodle-plugin-ci phpmd
    - moodle-plugin-ci codechecker
    - moodle-plugin-ci validate
    - if [ "$MOODLE_CI_VER" -eq 1 ] ; then moodle-plugin-ci csslint    ; fi
    - if [ "$MOODLE_CI_VER" -eq 1 ] ; then moodle-plugin-ci shifter    ; fi
    - if [ "$MOODLE_CI_VER" -eq 1 ] ; then moodle-plugin-ci jshint     ; fi
    - if [ "$MOODLE_CI_VER" -eq 2 ] ; then moodle-plugin-ci savepoints ; fi
    - if [ "$MOODLE_CI_VER" -eq 2 ] ; then moodle-plugin-ci mustache   ; fi
    - if [ "$MOODLE_CI_VER" -eq 2 ] ; then moodle-plugin-ci grunt      ; fi
    - if [ "$MOODLE_CI_VER" -eq 2 ] ; then moodle-plugin-ci phpdoc     ; fi
    - moodle-plugin-ci phpunit
    - moodle-plugin-ci behat

job1:
  image: moodlehq/moodle-php-apache:5.6
  variables:
    MOODLE_BRANCH: "MOODLE_29_STABLE"
    MOODLE_CI_VER: "1"
    DB: "mysqli"
    MYSQL_ROOT_PASSWORD: "superrootpass"
    DBUSER: "root"
    DBPASS: "superrootpass"
    DBHOST: "mysql"
  services:
    - mysql:5.7
  <<: *build_definition

job2:
  image: moodlehq/moodle-php-apache:5.6
  variables:
    MOODLE_BRANCH: "MOODLE_33_STABLE"
    DB: "mysqli"
    MYSQL_ROOT_PASSWORD: "superrootpass"
    DBUSER: "root"
    DBPASS: "superrootpass"
    DBHOST: "mysql"
  services:
    - mysql:5.7
  <<: *build_definition

job2a:
  variables:
    MOODLE_BRANCH: "MOODLE_33_STABLE"
    DB: "mysqli"
    MYSQL_ROOT_PASSWORD: "superrootpass"
    DBUSER: "root"
    DBPASS: "superrootpass"
    DBHOST: "mysql"
  services:
    - mysql:5.7
  <<: *build_definition

job3:
  variables:
    MOODLE_BRANCH: "MOODLE_34_STABLE"
    DB: "mysqli"
    MYSQL_ROOT_PASSWORD: "superrootpass"
    DBUSER: "root"
    DBPASS: "superrootpass"
    DBHOST: "mysql"
  services:
    - mysql:5.7
  <<: *build_definition
