
sudo: true

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

services:
  - mysql

env:
  global:
    - DB=mysqli
    - MOODLE_CI_VER=1
    - IGNORE_PATHS=vendor/composer
    - IGNORE_NAMES=autoload.php

matrix:
 include:
  - php: "5.6"
    env: MOODLE_BRANCH=MOODLE_29_STABLE
  - php: "5.6"
    env: MOODLE_BRANCH=MOODLE_30_STABLE
  - php: "5.6"
    env: MOODLE_BRANCH=MOODLE_31_STABLE
  - php: "5.6"
    env: MOODLE_BRANCH=MOODLE_32_STABLE MOODLE_CI_VER=2
  - php: "7.0"
    env: MOODLE_BRANCH=MOODLE_33_STABLE MOODLE_CI_VER=2
  - php: "7.0"
    env: MOODLE_BRANCH=MOODLE_34_STABLE MOODLE_CI_VER=2

before_install:
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^${MOODLE_CI_VER}
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

# We do not include behat testing for now since there are numerous issues
# with the tests them selves that need to be resolved before doing that.
script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - if [ "$MOODLE_CI_VER" -eq 2 ] ; then moodle-plugin-ci savepoints ; fi
