image:
  name: '271411534863.dkr.ecr.us-east-2.amazonaws.com/moodleusdev:latest'
  aws:
    access-key: $AWS_ACCESS_KEY
    secret-key: $AWS_SECRET_KEY

definitions:
  services:
    mariadb:
      image: mariadb:10
      variables:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'

pipelines:
  default:
    - step:
        name: 'Moodle 3.11, PHP 7.4 and MariaDB 10'
        script:
          - printenv ; pwd
          - '[ "$(pwd)" != "/var/tmp" ] && cd /var/tmp'
          - moodle-plugin-ci install --db-host='127.0.0.1'
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker || echo ''
          - moodle-plugin-ci validate || echo ''
          - moodle-plugin-ci savepoints || echo ''
          - moodle-plugin-ci mustache || echo ''
          - moodle-plugin-ci grunt || echo ''
          - moodle-plugin-ci phpdoc || echo ''
          - moodle-plugin-ci phpunit || echo ''
        services:
          - mariadb
    - step:
        name: 'Moodle 4.1, PHP 8.1 and MariaDB 10'
        script:
          - printenv ; pwd
          - '[ "$(pwd)" != "/var/tmp" ] && cd /var/tmp'
          - update-alternatives --set php /usr/bin/php8.1
          - moodle-plugin-ci install --db-host='127.0.0.1' --branch='MOODLE_401_STABLE'
          - moodle-plugin-ci phplint || echo ''
          - moodle-plugin-ci phpcpd || echo ''
          - moodle-plugin-ci phpmd || echo ''
          - moodle-plugin-ci codechecker || echo ''
          - moodle-plugin-ci validate || echo ''
          - moodle-plugin-ci savepoints || echo ''
          - moodle-plugin-ci mustache || echo ''
          - moodle-plugin-ci grunt || echo ''
          - moodle-plugin-ci phpdoc || echo ''
          - moodle-plugin-ci phpunit || echo ''
        services:
          - mariadb
