image:
  name: '271411534863.dkr.ecr.us-east-2.amazonaws.com/moodleusdev:latest'
  aws:
    access-key: $AWS_ACCESS_KEY
    secret-key: $AWS_SECRET_KEY

definitions:
  services:
    mariadb:
      image: mariadb:10
      variables:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    mysql:
      image: mysql:8
      variables:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    postgres:
      image: postgres:13
      variables:
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'secret'

pipelines:
  default:
    - step:
        name: 'Moodle 3.11, PHP 7.4 and MariaDB 10'
        script:
          - mkdir -pv "$BITBUCKET_CLONE_DIR/_workspace" && cd "$BITBUCKET_CLONE_DIR/_workspace"
          - cp -ru "$BITBUCKET_CLONE_DIR" /tmp/plugin
          - moodle-plugin-ci install --db-host='127.0.0.1' --plugin="$BITBUCKET_CLONE_DIR"
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker || echo ''
          - moodle-plugin-ci validate || echo ''
          - moodle-plugin-ci savepoints || echo ''
          - moodle-plugin-ci mustache || echo ''
          - moodle-plugin-ci grunt || echo ''
          - moodle-plugin-ci phpdoc || echo ''
          - moodle-plugin-ci phpunit || echo ''
        services:
          - mariadb
    - step:
        name: 'Moodle 4.1, PHP 8.1 and MariaDB 10'
        caches:
          - docker
        script:
          - export MOODLE_BEHAT_WWWROOT="http://$BITBUCKET_DOCKER_HOST_INTERNAL:8000"
          - export MOODLE_BEHAT_WDHOST="http://$BITBUCKET_DOCKER_HOST_INTERNAL:4444/wd/hub"
          - update-alternatives --set php /usr/bin/php8.1
          - cd /var/tmp
          - moodle-plugin-ci install --db-host='127.0.0.1' --plugin="$BITBUCKET_CLONE_DIR" --branch='MOODLE_401_STABLE'
          - docker run -d -p 4444:4444 --shm-size=1g -v "/var/tmp/moodle:/var/tmp/moodle" "selenium/standalone-firefox:3" 
            && { php -S 0.0.0.0:8000 -t "/var/tmp/moodle" > /dev/null 2>&1 & } ; sleep 10s ;
          - moodle-plugin-ci phplint || echo ''
          - moodle-plugin-ci phpcpd || echo ''
          - moodle-plugin-ci phpmd || echo ''
          - moodle-plugin-ci codechecker || echo ''
          - moodle-plugin-ci validate || echo ''
          - moodle-plugin-ci savepoints || echo ''
          - moodle-plugin-ci mustache || echo ''
          - moodle-plugin-ci grunt || echo ''
          - moodle-plugin-ci phpdoc || echo ''
          - moodle-plugin-ci phpunit || echo ''
          - moodle-plugin-ci behat || echo ''
        services:
          - mariadb
          - docker
    - step:
        name: 'Moodle 4.1, PHP 8.1 and PostgreSQL 13'
        script:
          - update-alternatives --set php /usr/bin/php8.1
          - cd /var/tmp
          - moodle-plugin-ci install --db-host='127.0.0.1' --db-user='root' --db-pass='secret'
            --plugin="$BITBUCKET_CLONE_DIR" --branch='MOODLE_401_STABLE'
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker
          - moodle-plugin-ci validate
          - moodle-plugin-ci savepoints
          - moodle-plugin-ci mustache
          - moodle-plugin-ci grunt
          - moodle-plugin-ci phpdoc
          - moodle-plugin-ci phpunit
        services:
          - postgres
    - step:
        name: 'Moodle 4.1, PHP 8.1 and MySQL 8'
        script:
          - update-alternatives --set php /usr/bin/php8.1
          - cd /var/tmp
          - moodle-plugin-ci install --db-host='127.0.0.1' --plugin="$BITBUCKET_CLONE_DIR" --branch='MOODLE_401_STABLE'
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker
          - moodle-plugin-ci validate
          - moodle-plugin-ci savepoints
          - moodle-plugin-ci mustache
          - moodle-plugin-ci grunt
          - moodle-plugin-ci phpdoc
          - moodle-plugin-ci phpunit
        services:
          - mysql
