image:
  name: '271411534863.dkr.ecr.us-east-2.amazonaws.com/moodleusdev:latest'
  aws:
    access-key: $AWS_ACCESS_KEY
    secret-key: $AWS_SECRET_KEY

definitions:
  services:
    mariadb:
      image: mariadb:10
      variables:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    mysql:
      image: mysql:5.7
      variables:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    postgres:
      image: postgres:13
      variables:
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'secret'
  caches:
    npm: $HOME/.npm

pipelines:
  default:
    - step:
        name: 'Moodle 3.11, PHP 7.4 and MariaDB 10'
        caches:
          - npm
          - composer
        script:
          - moodle-plugin-ci add-plugin --branch='3.9.0' jleyva/moodle-block_configurablereports
          - set-sshkey "$REPOKEY"
          - moodle-plugin-ci install --repo="$REPOSITORY" --branch='WORKPLACE_401_LATEST'
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker || echo ''
          - moodle-plugin-ci validate || echo ''
          - moodle-plugin-ci savepoints || echo ''
          - moodle-plugin-ci mustache || echo ''
          - moodle-plugin-ci grunt || echo ''
          - moodle-plugin-ci phpdoc || echo ''
          - moodle-plugin-ci phpunit || echo ''
        services:
          - mariadb
    - step:
        name: 'Moodle 4.1, PHP 8.1 and MariaDB 10'
        caches:
          - docker
          - npm
          - composer
        script:
          - setphpversion 8.1
          - moodle-plugin-ci install --branch='MOODLE_401_STABLE'
          - composer update --working-dir="$BITBUCKET_CLONE_DIR/moodle" -vvv
          - preset-start-behat
          - moodle-plugin-ci phplint || echo ''
          - moodle-plugin-ci phpcpd || echo ''
          - moodle-plugin-ci phpmd || echo ''
          - moodle-plugin-ci codechecker || echo ''
          - moodle-plugin-ci validate || echo ''
          - moodle-plugin-ci savepoints || echo ''
          - moodle-plugin-ci mustache || echo ''
          - moodle-plugin-ci grunt || echo ''
          - moodle-plugin-ci phpdoc || echo ''
          - moodle-plugin-ci phpunit || echo ''
          - moodle-plugin-ci behat || echo ''
        services:
          - mariadb
          - docker
    - step:
        name: 'Moodle 4.1, PHP 8.1 and PostgreSQL 13'
        caches:
          - npm
          - composer
        script:
          - setphpversion 8.1
          - moodle-plugin-ci install --db-type='pgsql' --db-user='root' --db-pass='secret'
            --branch='MOODLE_401_STABLE'
          - composer update --working-dir="$BITBUCKET_CLONE_DIR/moodle" -vvv
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker || echo ''
          - moodle-plugin-ci validate || echo ''
          - moodle-plugin-ci savepoints || echo ''
          - moodle-plugin-ci mustache || echo ''
          - moodle-plugin-ci grunt || echo ''
          - moodle-plugin-ci phpdoc || echo ''
          - moodle-plugin-ci phpunit || echo ''
        services:
          - postgres
    - step:
        name: 'Moodle 4.1, PHP 8.1 and MySQL 5.7'
        caches:
          - npm
          - composer
        script:
          - setphpversion 8.1
          - moodle-plugin-ci install --db-type='mysqli' --branch='MOODLE_401_STABLE'
          - composer update --working-dir="$BITBUCKET_CLONE_DIR/moodle" -vvv
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker || echo ''
          - moodle-plugin-ci validate || echo ''
          - moodle-plugin-ci savepoints || echo ''
          - moodle-plugin-ci mustache || echo ''
          - moodle-plugin-ci grunt || echo ''
          - moodle-plugin-ci phpdoc || echo ''
          - moodle-plugin-ci phpunit || echo ''
        services:
          - mysql
